#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20

// MAIN TEXTURE ID
#define ID_TEX_MARIO		30
#define ID_TEX_ENEMIES		40
#define ID_TEX_STAGE_TILES	50
#define ID_TEX_POWER_UPS	60


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BRICK_ARRAY 6
#define OBJECT_TYPE_BACK_PLATFORM 7
#define	OBJECT_TYPE_TUNNEL 8
#define OBJECT_TYPE_BIG_BUSH 9
#define OBJECT_TYPE_SMALL_BUSH 10
#define OBJECT_TYPE_MUSHROOM 11
#define OBJECT_TYPE_MYSTERY_BOX 12

#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#pragma region MAIN_TEXTURE

// GROUND TOP
#define ID_SPRITE_GROUND_TOP 60000
#define ID_SPRITE_GROUND_TOP_BEGIN (ID_SPRITE_CLOUD + 1000)
#define ID_SPRITE_GROUND_TOP_MIDDLE (ID_SPRITE_CLOUD + 2000)
#define ID_SPRITE_GROUND_TOP_END (ID_SPRITE_CLOUD + 3000)

// GROUND MIDDLE
#define ID_SPRITE_GROUND_MIDDLE 70000
#define ID_SPRITE_GROUND_MIDDLE_BEGIN (ID_SPRITE_CLOUD + 1000)
#define ID_SPRITE_GROUND_MIDDLE_MIDDLE (ID_SPRITE_CLOUD + 2000)
#define ID_SPRITE_GROUND_MIDDLE_END (ID_SPRITE_CLOUD + 3000)

// PLATFORM PINK
#define ID_SPRITE_PLATFORM_PINK 80000
#define ID_SPRITE_PLATFORM_PINK_TOP_LEFT (ID_SPRITE_PLATFORM_PINK + 1000)
#define ID_SPRITE_PLATFORM_PINK_TOP (ID_SPRITE_PLATFORM_PINK + 2000)
#define ID_SPRITE_PLATFORM_PINK_TOP_RIGHT (ID_SPRITE_PLATFORM_PINK + 3000)

#define ID_SPRITE_PLATFORM_PINK_MIDDLE_LEFT (ID_SPRITE_PLATFORM_PINK + 4000)
#define ID_SPRITE_PLATFORM_PINK_MIDDLE (ID_SPRITE_PLATFORM_PINK + 5000)
#define ID_SPRITE_PLATFORM_PINK_MIDDLE_RIGHT (ID_SPRITE_PLATFORM_PINK + 6000)

#define ID_SPRITE_PLATFORM_PINK_BOTTOM_LEFT (ID_SPRITE_PLATFORM_PINK + 7000)
#define ID_SPRITE_PLATFORM_PINK_BOTTOM (ID_SPRITE_PLATFORM_PINK + 8000)
#define ID_SPRITE_PLATFORM_PINK_BOTTOM_RIGHT (ID_SPRITE_PLATFORM_PINK + 9000)


// PLATFORM GREEN
#define ID_SPRITE_PLATFORM_GREEN 90000
#define ID_SPRITE_PLATFORM_GREEN_TOP_LEFT (ID_SPRITE_PLATFORM_GREEN + 1000)
#define ID_SPRITE_PLATFORM_GREEN_TOP (ID_SPRITE_PLATFORM_GREEN + 2000)
#define ID_SPRITE_PLATFORM_GREEN_TOP_RIGHT (ID_SPRITE_PLATFORM_GREEN + 3000)

#define ID_SPRITE_PLATFORM_GREEN_MIDDLE_LEFT (ID_SPRITE_PLATFORM_GREEN + 4000)
#define ID_SPRITE_PLATFORM_GREEN_MIDDLE (ID_SPRITE_PLATFORM_GREEN + 5000)
#define ID_SPRITE_PLATFORM_GREEN_MIDDLE_RIGHT (ID_SPRITE_PLATFORM_GREEN + 6000)

#define ID_SPRITE_PLATFORM_GREEN_BOTTOM_LEFT (ID_SPRITE_PLATFORM_GREEN + 7000)
#define ID_SPRITE_PLATFORM_GREEN_BOTTOM (ID_SPRITE_PLATFORM_GREEN + 8000)
#define ID_SPRITE_PLATFORM_GREEN_BOTTOM_RIGHT (ID_SPRITE_PLATFORM_GREEN + 9000)


// PLATFORM BLUE
#define ID_SPRITE_PLATFORM_BLUE 100000
#define ID_SPRITE_PLATFORM_BLUE_TOP_LEFT (ID_SPRITE_PLATFORM_BLUE + 1000)
#define ID_SPRITE_PLATFORM_BLUE_TOP (ID_SPRITE_PLATFORM_BLUE + 2000)
#define ID_SPRITE_PLATFORM_BLUE_TOP_RIGHT (ID_SPRITE_PLATFORM_BLUE + 3000)

#define ID_SPRITE_PLATFORM_BLUE_MIDDLE_LEFT (ID_SPRITE_PLATFORM_BLUE + 4000)
#define ID_SPRITE_PLATFORM_BLUE_MIDDLE (ID_SPRITE_PLATFORM_BLUE + 5000)
#define ID_SPRITE_PLATFORM_BLUE_MIDDLE_RIGHT (ID_SPRITE_PLATFORM_BLUE + 6000)

#define ID_SPRITE_PLATFORM_BLUE_BOTTOM_LEFT (ID_SPRITE_PLATFORM_BLUE + 7000)
#define ID_SPRITE_PLATFORM_BLUE_BOTTOM (ID_SPRITE_PLATFORM_BLUE + 8000)
#define ID_SPRITE_PLATFORM_BLUE_BOTTOM_RIGHT (ID_SPRITE_PLATFORM_BLUE + 9000)


// PLATFORM WHITE
#define ID_SPRITE_PLATFORM_WHITE 110000
#define ID_SPRITE_PLATFORM_WHITE_TOP_LEFT (ID_SPRITE_PLATFORM_WHITE + 1000)
#define ID_SPRITE_PLATFORM_WHITE_TOP (ID_SPRITE_PLATFORM_WHITE + 2000)
#define ID_SPRITE_PLATFORM_WHITE_TOP_RIGHT (ID_SPRITE_PLATFORM_WHITE + 3000)

#define ID_SPRITE_PLATFORM_WHITE_MIDDLE_LEFT (ID_SPRITE_PLATFORM_WHITE + 4000)
#define ID_SPRITE_PLATFORM_WHITE_MIDDLE (ID_SPRITE_PLATFORM_WHITE + 5000)
#define ID_SPRITE_PLATFORM_WHITE_MIDDLE_RIGHT (ID_SPRITE_PLATFORM_WHITE + 6000)

#define ID_SPRITE_PLATFORM_WHITE_BOTTOM_LEFT (ID_SPRITE_PLATFORM_WHITE + 7000)
#define ID_SPRITE_PLATFORM_WHITE_BOTTOM (ID_SPRITE_PLATFORM_WHITE + 8000)
#define ID_SPRITE_PLATFORM_WHITE_BOTTOM_RIGHT (ID_SPRITE_PLATFORM_WHITE + 9000)


// MISTERY BLOCK
#define ID_SPRITE_MISTERY_BLOCK 120000
#define ID_SPRITE_MISTERY_BLOCK_1 (ID_SPRITE_MISTERY_BLOCK + 1000)
#define ID_SPRITE_MISTERY_BLOCK_2 (ID_SPRITE_MISTERY_BLOCK + 2000)
#define ID_SPRITE_MISTERY_BLOCK_3 (ID_SPRITE_MISTERY_BLOCK + 3000)
#define ID_SPRITE_MISTERY_BLOCK_4 (ID_SPRITE_MISTERY_BLOCK + 4000)

// WOOD BLOCK
#define ID_SPRITE_WOOD_BLOCK 130000

// CLOUD BLOCK
#define ID_SPRITE_CLOUD_BLOCK 140000
#define ID_SPRITE_CLOUD_BLOCK_BEGIN_1 (ID_SPRITE_CLOUD_BLOCK + 1000)
#define ID_SPRITE_CLOUD_BLOCK_BEGIN_2 (ID_SPRITE_CLOUD_BLOCK + 2000)
#define ID_SPRITE_CLOUD_BLOCK_MIDDLE_1 (ID_SPRITE_CLOUD_BLOCK + 3000)
#define ID_SPRITE_CLOUD_BLOCK_MIDDLE_2 (ID_SPRITE_CLOUD_BLOCK + 4000)
#define ID_SPRITE_CLOUD_BLOCK_END_1 (ID_SPRITE_CLOUD_BLOCK + 5000)
#define ID_SPRITE_CLOUD_BLOCK_END_2 (ID_SPRITE_CLOUD_BLOCK + 6000)

// BUSH
#define ID_SPRITE_BUSH 150000

// BIG BUSH
#define ID_SPRITE_BIG_BUSH 160000
#define ID_SPRITE_BIG_BUSH_TOP_1 (ID_SPRITE_BIG_BUSH + 1000)
#define ID_SPRITE_BIG_BUSH_TOP_2 (ID_SPRITE_BIG_BUSH + 2000)
#define ID_SPRITE_BIG_BUSH_EDGE_1 (ID_SPRITE_BIG_BUSH + 3000)
#define ID_SPRITE_BIG_BUSH_EDGE_2 (ID_SPRITE_BIG_BUSH + 4000)
#define ID_SPRITE_BIG_BUSH_CENTER (ID_SPRITE_BIG_BUSH + 10000)
#define ID_SPRITE_BIG_BUSH_TOP_BLEND_1 (ID_SPRITE_BIG_BUSH + 5000) 
#define ID_SPRITE_BIG_BUSH_TOP_BLEND_2 (ID_SPRITE_BIG_BUSH + 6000)




#pragma endregion